version: '3.8'

services:
  api-gateway:
    build: ./ApiGateway
    ports:
      - "5000:80"
    depends_on:
      - task-queue

  task-queue:
    build: ./TaskQueue
    ports:
      - "5001:80"
    depends_on:
      - task-executor

  task-executor:
    build: ./TaskExecutor
    ports:
      - "5002:80"

  database:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tasksdb
    ports:
      - "5432:5432"

  monitoring:
    build: ./MonitoringService
    ports:
      - "9090:9090"  # Пример для Prometheus
