version: '3.8'

services:
  apigateway:
    image: yourusername/apigateway:latest
    build:
      context: ./ApiGateway
      dockerfile: Dockerfile
    ports:
      - "5000:80" # Проброс порта для ApiGateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - TaskQueue__BaseUrl=http://taskqueue:80 # URL для TaskQueue
    depends_on:
      - taskqueue

  taskqueue:
    image: yourusername/taskqueue:latest
    build:
      context: ./
      dockerfile: ./TaskQueue/Dockerfile
    ports:
      - "5001:5001" # Проброс порта для TaskQueue
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=taskqueue;Username=postgres;Password=yourpassword
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__QueueName=taskqueue

#  taskexecutor:
#    image: yourusername/taskexecutor:latest
#    build:
#      context: ./TaskExecutor
#      dockerfile: Dockerfile
#    environment:
#      - ASPNETCORE_ENVIRONMENT=Development
#      - RabbitMQ__Host=rabbitmq
#      - RabbitMQ__QueueName=taskqueue

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "15672:15672" # Web UI RabbitMQ
      - "5672:5672" # AMQP
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  db:
    image: postgres:latest
    ports:
      - "5432:5432" # Проброс порта для PostgreSQL
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: taskqueue
    volumes:
      - postgres_data:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090" # Проброс порта для Prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml # Конфигурационный файл Prometheus
    depends_on:
      - apigateway
      - taskqueue

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000" # Проброс порта для Grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

volumes:
  postgres_data:
