global:
  scrape_interval: 15s # Как часто Prometheus будет собирать метрики
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'apigateway'
    static_configs:
      - targets: ['apigateway:80'] # Сервис apigateway

  - job_name: 'taskqueue'
    static_configs:
      - targets: ['taskqueue:80'] # Сервис taskqueue

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15672'] # RabbitMQ

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] # Сам Prometheus
